# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-16 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('script', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.IntegerField(choices=[(0, 'private'), (1, 'group'), (2, 'discuss'), (3, 'group_upload'), (4, 'group_admin'), (5, 'group_decrease'), (6, 'group_increase'), (7, 'friend_add'), (8, 'add_friend_request'), (9, 'add_group_request')])),
                ('registrant_id', models.CharField(max_length=30)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='script.PythonScript')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=30)),
                ('script_type', models.IntegerField()),
                ('group_script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='script.Command')),
            ],
        ),
    ]
