# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-17 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0001_initial'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discuss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discuss_id', models.CharField(max_length=30)),
                ('registrant_id', models.CharField(max_length=30)),
                ('discuss_script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='script.Command')),
            ],
        ),
        migrations.CreateModel(
            name='Private',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_id', models.CharField(max_length=30)),
                ('registrant_id', models.CharField(max_length=30)),
                ('private_script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='script.Command')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='registrant_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='script',
        ),
        migrations.RemoveField(
            model_name='group',
            name='script_type',
        ),
        migrations.AddField(
            model_name='group',
            name='registrant_id',
            field=models.CharField(default='1', max_length=30),
        ),
    ]
