# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-17 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20181117_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='registrant_id',
            field=models.CharField(max_length=30),
        ),
    ]
