# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-17 07:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20181117_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='discuss',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 17, 15, 37, 9, 948413)),
        ),
        migrations.AddField(
            model_name='group',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 17, 15, 37, 9, 947571)),
        ),
        migrations.AddField(
            model_name='private',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 17, 15, 37, 9, 947989)),
        ),
    ]
