# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-17 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20181117_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discuss',
            name='add_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='add_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='private',
            name='add_time',
            field=models.DateTimeField(),
        ),
    ]
