# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-17 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20181117_1537'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
