# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-25 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0005_help'),
        ('event', '0006_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_id', models.CharField(max_length=30)),
                ('registrant_id', models.CharField(max_length=30)),
                ('add_time', models.DateTimeField()),
                ('private_script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='script.Command')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discuss_id', models.CharField(max_length=30)),
                ('registrant_id', models.CharField(max_length=30)),
                ('add_time', models.DateTimeField()),
                ('discuss_script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='script.Command')),
            ],
        ),
        migrations.RenameModel(
            old_name='Group',
            new_name='Message',
        ),
        migrations.RenameModel(
            old_name='Discuss',
            new_name='Meta_event',
        ),
        migrations.RemoveField(
            model_name='private',
            name='private_script',
        ),
        migrations.DeleteModel(
            name='Private',
        ),
    ]
