# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-09 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20181125_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='group_script',
        ),
        migrations.RemoveField(
            model_name='meta_event',
            name='discuss_script',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='private_script',
        ),
        migrations.RemoveField(
            model_name='request',
            name='discuss_script',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Meta_event',
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
