# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-09 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('script', '0006_auto_20181128_1921'),
        ('event', '0008_auto_20181209_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_id', models.CharField(max_length=30)),
                ('add_time', models.DateTimeField(auto_now=True)),
                ('error_num', models.IntegerField(default=0)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='script.PythonScript')),
            ],
        ),
        migrations.CreateModel(
            name='Meta_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_id', models.CharField(max_length=30)),
                ('add_time', models.DateTimeField(auto_now=True)),
                ('error_num', models.IntegerField(default=0)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='script.PythonScript')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_id', models.CharField(max_length=30)),
                ('add_time', models.DateTimeField(auto_now=True)),
                ('error_num', models.IntegerField(default=0)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='script.PythonScript')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_id', models.CharField(max_length=30)),
                ('add_time', models.DateTimeField(auto_now=True)),
                ('error_num', models.IntegerField(default=0)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='script.PythonScript')),
            ],
        ),
    ]
