# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-09 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_message_meta_event_notice_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_ban',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meta_event',
            name='is_ban',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notice',
            name='is_ban',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='is_ban',
            field=models.BooleanField(default=False),
        ),
    ]
