# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-11 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20181209_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': '消息', 'verbose_name_plural': '消息'},
        ),
        migrations.AlterModelOptions(
            name='meta_event',
            options={'verbose_name': '源事件', 'verbose_name_plural': '源事件'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': '公告', 'verbose_name_plural': '公告'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': '请求', 'verbose_name_plural': '请求'},
        ),
        migrations.AlterField(
            model_name='message',
            name='add_time',
            field=models.DateTimeField(auto_now=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='message',
            name='error_num',
            field=models.IntegerField(default=0, verbose_name='错误次数'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_ban',
            field=models.BooleanField(default=False, verbose_name='已禁用'),
        ),
        migrations.AlterField(
            model_name='message',
            name='register_id',
            field=models.CharField(max_length=30, verbose_name='注册者ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='script.PythonScript', verbose_name='脚本'),
        ),
        migrations.AlterField(
            model_name='meta_event',
            name='add_time',
            field=models.DateTimeField(auto_now=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='meta_event',
            name='error_num',
            field=models.IntegerField(default=0, verbose_name='错误次数'),
        ),
        migrations.AlterField(
            model_name='meta_event',
            name='is_ban',
            field=models.BooleanField(default=False, verbose_name='已禁用'),
        ),
        migrations.AlterField(
            model_name='meta_event',
            name='register_id',
            field=models.CharField(max_length=30, verbose_name='注册者ID'),
        ),
        migrations.AlterField(
            model_name='meta_event',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='script.PythonScript', verbose_name='脚本'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='add_time',
            field=models.DateTimeField(auto_now=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='error_num',
            field=models.IntegerField(default=0, verbose_name='错误次数'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='is_ban',
            field=models.BooleanField(default=False, verbose_name='已禁用'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='register_id',
            field=models.CharField(max_length=30, verbose_name='注册者ID'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='script.PythonScript', verbose_name='脚本'),
        ),
        migrations.AlterField(
            model_name='request',
            name='add_time',
            field=models.DateTimeField(auto_now=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='request',
            name='error_num',
            field=models.IntegerField(default=0, verbose_name='错误次数'),
        ),
        migrations.AlterField(
            model_name='request',
            name='is_ban',
            field=models.BooleanField(default=False, verbose_name='已禁用'),
        ),
        migrations.AlterField(
            model_name='request',
            name='register_id',
            field=models.CharField(max_length=30, verbose_name='注册者ID'),
        ),
        migrations.AlterField(
            model_name='request',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='script.PythonScript', verbose_name='脚本'),
        ),
    ]
