# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-23 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='user_name',
        ),
    ]
