# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-28 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_creator_user_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Creator',
            new_name='User',
        ),
    ]
