# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-16 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_name', models.TextField()),
                ('last_bind_user_id', models.CharField(max_length=20)),
                ('last_bind_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PythonScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='脚本名字')),
                ('path', models.TextField(verbose_name='脚本路径')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Creator')),
            ],
        ),
        migrations.AddField(
            model_name='command',
            name='inside_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='script.PythonScript'),
        ),
    ]
