# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-23 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0002_auto_20181123_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='is_ban',
            field=models.BooleanField(default=False),
        ),
    ]
