# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-24 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0003_command_is_ban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='inside_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='script.PythonScript'),
        ),
    ]
