# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-28 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0005_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythonscript',
            name='creator',
            field=models.CharField(max_length=20),
        ),
    ]
