# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-11 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0006_auto_20181128_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='command',
            options={'verbose_name': '命令', 'verbose_name_plural': '命令'},
        ),
        migrations.AlterModelOptions(
            name='help',
            options={'verbose_name': '帮助', 'verbose_name_plural': '帮助'},
        ),
        migrations.AlterModelOptions(
            name='pythonscript',
            options={'verbose_name': '脚本', 'verbose_name_plural': '脚本'},
        ),
    ]
